### ISSUE TITLE
custom path does not support variables

### ISSUE THREAD

**Issue by andidev** [neverendingqs/serverless-dotenv-plugin#52]
for example this works for me:
```
path: .env.dev
```

but this does not
```
path: .env.${'dev'}
```

**Comment by SimonHoiberg** [comment]
+1 on this one.
I would love to be able to do something like this:
```yml
dotenv:
    path: 'deployment/${self:provider.stage}/.env'
```

**Comment by neverendingqs** [comment]
I _think_ you might find more mileage with the [built-in dotenv support](https://www.serverless.com/framework/docs/environment-variables/)? Unfortunately, it does not allow for custom paths - the dotenv file must live in the root directory of the project.

As noted in https://github.com/neverendingqs/serverless-dotenv-plugin/issues/38#issuecomment-772052144,

> Variable references in the serverless instance are not resolved before a Plugin's constructor is called, so if you need these, make sure to wait to access those from your hooks.
> ~https://www.serverless.com/framework/docs/providers/aws/guide/plugins/#plugins/

. We do everything in the constructor today to try to be the first thing that happens when Serverless does its thing. However, that means. Serverless hasn't interpolated the values for us at that time.

There might be a way to trigger interpolation, but it might be via a non-public API, which isn't a great option.

Unfortunately, I do not have a workaround at time. Open to ideas!

**Comment by neverendingqs** [comment]
I thought about this more, and I think there are sufficient alternatives that I am comfortable closing this with `wontfix`. I added some workarounds in https://github.com/neverendingqs/serverless-dotenv-plugin/pull/106.

Please feel free to reopen if you have additional feedback. Thanks!
