### ISSUE TITLE
Feature request: use default configured stage when no env or stage is provided on command line

### ISSUE THREAD

**Issue by jsw** [neverendingqs/serverless-dotenv-plugin#56]
I notice that `.env` is being used when no `--env` or `--stage` is set. I would expect it to then default to the stage set in `serverless.yml`.

```
provider:
  stage: dev
```

When I do something like `sls deploy` it is picking up `.env` instead of `.env.dev`. I have to explicitly do `sls deploy -s dev` to pick up the right file.

**Comment by colynb** [comment]
I see what you're saying but if you look at the example app, you can see that in the yaml file
```
provider:
  name: aws
  runtime: nodejs6.10
  region: ${env:REGION}
  stage: ${env:STAGE}
```
the stage is set with an environment variable. In most use cases that I've experienced, this is common. I can't rely on stage being hardcoded in the way you want because it will need to be parsed using variables found in the env file.

**Comment by jsw** [comment]
Makes sense. I didn't realize that `stage: ${env:STAGE}` was a thing.
