### ISSUE TITLE
Name resolution stop working when I set `path` and `basePath` options

### ISSUE THREAD

**Issue by zhaoyi0113** [neverendingqs/serverless-dotenv-plugin#60]
I configured this plugin in `serverless.yml` as below:

```
custom:
  dotenv:
      basePath: config
      path: config/.env
```

I have some env files under `config` directory:

```
config/.env
config/.env.joey
```

when I deploy with a stage name `joey`, e.g. `sls deploy --stage joey`, it still loads file `config.env`. It doesn't look at `config.env.joey`. The output is always:

```
Serverless: DOTENV: Loading environment variables from config/.env:
```

If I remove the option `basePath` and `path` from `serverless.yml` file and put these env files in the default location which is `./`. Everything works fine. Could you support automatic name resolution with customised path?

**Comment by zhaoyi0113** [comment]
Ok, I figured out how it works. When I specify `path`, it will ignore `basePath` configuration and name resolution. Is it true? If yes, I can't specify a different file name?

**Comment by snavarro89** [comment]
Did you ever got this to work?

**Comment by neverendingqs** [comment]
> Ok, I figured out how it works. When I specify `path`, it will ignore `basePath` configuration and name resolution. Is it true? If yes, I can't specify a different file name?

That is correct. If `path` is provided, `basePath` is ignored: https://github.com/neverendingqs/serverless-dotenv-plugin/blob/2b66c1550bdbeb06be477cb068f4e41ad67f1339/index.js#L46-L71

From the README:

> This will disable automatic env file resolution

Could you describe your use case more? Are you looking to load environment variables from both `config/.env.joey` and `config/.env` when you run `sls deploy --stage joey`?

**Comment by aldex32** [comment]
Hi @neverendingqs ,
As described in the documentation, when setting the property `path` it disables the automatic env file resolution. Why so? Can we still have the resolution even when using a different path? Or is this a limitation in the `dotenv` library?

**Comment by aldex32** [comment]
Nevermind, `basePath` is the way to go.

**Comment by pflugs30** [comment]
One comment about the `basePath` option.  I configured my `serverless.yml` file to load from a folder containing all my env files, but the plugin consistently couldn't find them or resolve the environment names.  I resolved the problem when I added a trailing '/' character to the property, like this:

```
  dotenv:
    basePath: env/
```

Note: I am developing on Windows 10 with Visual Studio Code.  Perhaps other people may have different results on different platforms?  Otherwise, perhaps [this line](https://github.com/neverendingqs/serverless-dotenv-plugin/blob/b3259efc9fdc9dddc9ad5e0cbf6ac581bc6f949c/src/index.js#L88) should use some kind of environment specific path combine function?
